source 'https://supermarket.getchef.com'

cookbook 'ark'
cookbook 'build-essential'
cookbook 'elasticsearch', github: 'elasticsearch/cookbook-elasticsearch'
cookbook 'ipaddr_extensions'
cookbook 'java'
cookbook 'mosh'
cookbook 'rsyslog'
cookbook 'sysctl'
cookbook 'ulimit'
